//Author:    Max Howell <max.howell@methylblue.com>, (C) 2003-4
//Copyright: See COPYING file that comes with this distribution

#ifndef SETTINGSDLG_H
#define SETTINGSDLG_H

#include "ui_dialog.h" //generated by uic
#include <qtimer.h>
//Added by qt3to4:
#include <QCloseEvent>


class SettingsDialog : public QWidget, public Ui_Dialog
{
  Q_OBJECT

public:
  SettingsDialog( QWidget* parent =0, const char* =0 )
	  : QWidget(parent)
  { setupUi(this); }

protected:
  virtual void closeEvent( QCloseEvent * );
  virtual void reject();

public slots:
  void addDirectory();
  void removeDirectory();
  void toggleScanAcrossMounts( bool );
  void toggleDontScanRemoteMounts( bool );
  void toggleDontScanRemovableMedia( bool );
  void reset();
  void startTimer();
  void toggleUseAntialiasing( bool = true );
  void toggleVaryLabelFontSizes( bool );
  void changeContrast( int );
  void changeScheme( int );
  void changeMinFontPitch( int );
  void toggleShowSmallFiles( bool );
  void slotSliderReleased();

signals:
  void mapIsInvalid();
  void canvasIsDirty( int );

private:
  QTimer m_timer;

  static const uint TIMEOUT=1000;
};

#endif
